name: setup-tar-creation

on: 
    workflow_dispatch:
    push:
        branches:
        - main

env:
  REGISTRY: ghcr.io/microsoft
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-tar-file:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2

    - uses: microsoft/azure-orbital-space-sdk-github-actions/composite-actions/initialize@km/add_structure
      with:
        env_file: ./env/spacefx.env
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and package tar file
      shell: bash
      run: |
        source "./modules/load_modules.sh" $@ --log_dir /var/log

        info_log "Running ./.vscode/build_setup_tarball.sh"
        run_a_script "./.vscode/build_setup_tarball.sh"
        
        sub_exit_code=${PIPESTATUS[0]}
        if [[ $sub_exit_code -gt 0 ]]; then
            echo "Previous step failed.  Troubleshoot"
            exit 1
        fi
